shell=tmux -u new-session -A -s Main

font=MesloLGS NF:size=13
# font=JetBrainsMono Nerd Font:size=14

pad=4x4 center

term=xterm-256color

[scrollback]
lines=10000
multiplier=1.0

[colors-dark]
background=282c32
foreground=c9cdd5

cursor=000000 eeeeee
regular0=21252b
regular1=e06c75
regular2=98c379
regular3=e5c07b
regular4=61afef
regular5=c678dd
regular6=56b6c2
regular7=abb2bf
bright0=767676
bright1=e06c75
bright2=98c379
bright3=e5c07b
bright4=61afef
bright5=c678dd
bright6=56b6c2
bright7=abb2bf
selection-background=323844
selection-foreground=abb2bf

# May be flickering
[tweak]
delayed-render-lower=0
delayed-render-upper=0
