#!/bin/bash

# Personal workflow for plaintext journaling
# - Downloads images/videos from local immich instance to markdown folder
# - Adds headers and captions, converting to common formats
# - Previews images to allow quick selection of images

# Validate import of environment variables
source "$HOME/dotfiles/scripts/.env"

: "${IMMICH_ENDPOINT:? "IMMICH_ENDPOINT is not set"}"
: "${IMMICH_APIKEY:? "IMMICH_APIKEY is not set"}"
: "${JOURNAL_FOLDER:? "JOURNAL_FOLDER is not set"}"

JOURNAL_FILE="$JOURNAL_FOLDER/journal.md"
DAYS_RANGE=0 # Default range

show_help() {
    echo "Usage: journal [FLAGS]"
    echo ""
    echo "FLAGS:"
    echo "  -o       Quick open the journal in Neovim and exit"
    echo "  -l       Print last 5 days logged in journal and exit"
    echo "  -d DAYS  Set the date search range in days (default: $DAYS_RANGE)"
    echo "  -h       Show this help message"
}

while getopts "lod:h" opt; do
    case "$opt" in
    l)
        cat "$JOURNAL_FILE" |
            rg "^# " |
            tail -n 5 |
            cut -c 3- |
            tac |
            while read -r entry_date; do
                seconds_diff=$(($(date +%s) - $(date -ud "$entry_date" +%s)))
                date_diff=$((seconds_diff / 86400 - 1))
                echo "$entry_date (-$date_diff days)"
            done
        exit 0
        ;;
    o)
        cd "$JOURNAL_FOLDER" || exit 1
        nvim "$JOURNAL_FILE" +"norm G"
        exit 0
        ;;
    d) DAYS_RANGE=$OPTARG ;;
    h)
        show_help
        exit 0
        ;;
    *)
        show_help
        exit 1
        ;;
    esac
done

shopt -s nocaseglob
mkdir -p "$JOURNAL_FOLDER/imgs"
TMP_DIR=$(mktemp -d -t immich_journal_XXXXXX)
trap 'rm -rf "$TMP_DIR"' EXIT

immich() {
    curl \
        -H "x-api-key: $IMMICH_APIKEY" \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        "$@"
}

download_from_immich() {
    local DATE=$1

    if [[ -z "$DATE" ]]; then
        echo "Error: No date provided. Usage: download_from_immich YYYY_MM_DD"
        return 1
    fi

    DASHED_DATE=$(echo "$DATE" | tr '_' '-')
    echo -e "\n# ${DASHED_DATE}\n" >>"$JOURNAL_FILE"

    START_SEARCH=$(date -d "$DASHED_DATE 00:00:00 $DAYS_RANGE days ago" -Is)
    END_SEARCH=$(date -d "$DASHED_DATE 23:59:59 $DAYS_RANGE days" -Is)

    # Fetch images in the given date, +/- $DAYS_RANGE
    RES=$(immich \
        -sX POST "$IMMICH_ENDPOINT/search/metadata" \
        -d "{
          \"takenAfter\": \"${START_SEARCH}\",
          \"takenBefore\": \"${END_SEARCH}\",
          \"size\": 100
        }" |
        jq -r '.assets.items[] | "\(.id) \(.type) \(.originalFileName)"')

    echo "$RES" | while read -r UUID TYPE ORIGINAL_FILENAME; do
        TEMP_FILE="/${TMP_DIR}/$UUID.orig"
        echo "Downloading $UUID ($TYPE)"

        # Download asset to TMP_DIR
        immich \
            -sX GET "$IMMICH_ENDPOINT/assets/$UUID/original" \
            -o "$TEMP_FILE"

        # Preview image/video based on type
        if [[ "$TYPE" == "IMAGE" ]]; then
            feh --scale-down "$TEMP_FILE" &
        else
            mpv --loop "$TEMP_FILE" &>/dev/null &
        fi

        PREVIEW_PID=$!

        echo -n "Action for $TYPE [y: save, n: next, N: skip remaining]: "
        read -n 1 -r ADD_ASSET </dev/tty
        echo ""

        kill $PREVIEW_PID 2>/dev/null
        wait $PREVIEW_PID 2>/dev/null

        if [[ $ADD_ASSET == "N" ]]; then
            echo "Skipping remaining assets..."
            break
        fi

        # Relabel asset with date and custom label
        if [[ $ADD_ASSET == "y" ]]; then
            read -rp "Enter a label for the file: " LABEL </dev/tty

            # Convert [example_label_name] to [Example Label Name], for default name
            CLEAN_LABEL=$(
                echo "$LABEL" |
                    sed 's/[_-]/ /g' |
                    awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1'
            )

            if [[ "$TYPE" == "IMAGE" ]]; then
                # Convert images to pngs
                magick "${TEMP_FILE}" "${JOURNAL_FOLDER}/imgs/${DATE}_${LABEL}.png"
                rm "${TEMP_FILE}"
                echo "![${CLEAN_LABEL}](./imgs/${DATE}_${LABEL}.png)" >>"$JOURNAL_FILE"
            else
                EXT="${ORIGINAL_FILENAME##*.}"
                mv "${TEMP_FILE}" "${JOURNAL_FOLDER}/imgs/${DATE}_${LABEL}.${EXT}"
                echo "![${CLEAN_LABEL}](./imgs/${DATE}_${LABEL}.${EXT})" >>"$JOURNAL_FILE"
            fi
        fi
    done
}

DEFAULT_DATE=$(date +"%Y_%m_%d")
read -rep "Enter the date of entry: " -i "$DEFAULT_DATE" ENTRY_DATE
ENTRY_DATE=${ENTRY_DATE:-$DEFAULT_DATE}

download_from_immich "${ENTRY_DATE}"

nvim "$JOURNAL_FILE" +"norm G"
