#!/bin/bash

# Personal workflow for plaintext journaling
# - Downloads images/videos from local immich instance to markdown folder
# - Adds headers and captions, converting to common formats
# - Previews images to allow quick selection of images

# Validate import of environment variables
source "$HOME/dotfiles/scripts/.env"

: "${IMMICH_ENDPOINT:? "IMMICH_ENDPOINT is not set"}"
: "${IMMICH_APIKEY:? "IMMICH_APIKEY is not set"}"
: "${JOURNAL_FOLDER:? "JOURNAL_FOLDER is not set"}"

JOURNAL_FILE="$JOURNAL_FOLDER/journal.md"

# Quick open journal
if [[ "$1" == "-o" ]]; then
    cd "$JOURNAL_FOLDER" || exit 0
    nvim "$JOURNAL_FILE" +"norm G"
    exit 0
fi

shopt -s nocaseglob
mkdir -p "$JOURNAL_FOLDER/imgs"
TMP_DIR=$(mktemp -d -t immich_journal_XXXXXX)
trap 'rm -rf "$TMP_DIR"' EXIT

immich() {
    curl \
        -H "x-api-key: $IMMICH_APIKEY" \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        "$@"
}

download_from_immich() {
    local DATE=$1

    if [[ -z "$DATE" ]]; then
        echo "Error: No date provided. Usage: download_from_immich YYYY_MM_DD"
        return 1
    fi

    DASHED_DATE=$(echo "$DATE" | tr '_' '-')
    echo -e "\n# ${DASHED_DATE}\n" >>"$JOURNAL_FILE"

    START_SEARCH=$(date -d "$DASHED_DATE - 1 day" +"%Y-%m-%dT00:00:00Z")
    END_SEARCH=$(date -d "$DASHED_DATE + 1 day" +"%Y-%m-%dT23:59:59Z")

    # Fetch images in the given date, +/- 1 day (for time zone purposes)
    RES=$(immich \
        -sX POST "$IMMICH_ENDPOINT/search/metadata" \
        -d "{
          \"takenAfter\": \"${START_SEARCH}\",
          \"takenBefore\": \"${END_SEARCH}\",
          \"size\": 100
        }" |
        jq -r '.assets.items[] | "\(.id) \(.type) \(.originalFileName)"')

    echo "$RES" | while read -r UUID TYPE ORIGINAL_FILENAME; do
        TEMP_FILE="/${TMP_DIR}/$UUID.orig"
        echo "Downloading $UUID ($TYPE)"

        # Download asset to TMP_DIR
        immich \
            -sX GET "$IMMICH_ENDPOINT/assets/$UUID/original" \
            -o "$TEMP_FILE"

        # Preview image/video based on type
        if [[ "$TYPE" == "IMAGE" ]]; then
            feh --scale-down "$TEMP_FILE"
        else
            mpv "$TEMP_FILE" &>/dev/null
        fi

        read -rp "Save this $TYPE? (y/n): " ADD_ASSET </dev/tty

        # Relabel asset with date and custom label
        if [[ $ADD_ASSET == "y" ]]; then
            read -rp "Enter a label for the file: " LABEL </dev/tty

            if [[ "$TYPE" == "IMAGE" ]]; then
                # Convert images to pngs
                magick "${TEMP_FILE}" "${JOURNAL_FOLDER}/imgs/${DATE}_${LABEL}.png"
                rm "${TEMP_FILE}"
                echo "![${LABEL}](./imgs/${DATE}_${LABEL}.png)" >> "$JOURNAL_FILE"
            else
                EXT="${ORIGINAL_FILENAME##*.}"
                mv "${TEMP_FILE}" "${JOURNAL_FOLDER}/imgs/${DATE}_${LABEL}.${EXT}"
                echo "![${LABEL}](./imgs/${DATE}_${LABEL}.${EXT})" >> "$JOURNAL_FILE"
            fi
        fi
    done
}

DEFAULT_DATE=$(date +"%Y_%m_%d")
read -rep "Enter the date of entry: " -i "$DEFAULT_DATE" ENTRY_DATE
ENTRY_DATE=${ENTRY_DATE:-$DEFAULT_DATE}

download_from_immich "${ENTRY_DATE}"

nvim "$JOURNAL_FILE" +"norm G"
