#!/bin/bash

# Spins up an ephemeral NixOS VM passing through nix store
# to create a true VM jail with access to Nix and the bare minimum
# dependencies for Opencode to run with nix-direnv enabled

# Uses current directory by default, can also pass in folder
nix run "$HOME/dotfiles/scripts/microjail-nix#microjail"
