#!/bin/bash

# Launches tmux session with relevant obsidian vault files

SESSION_NAME="Obsidian"
COMMAND="cd ~/Desktop/Obsidian/Eric; nvim ~/Desktop/Obsidian/Eric/Scratchpad.md"

if ! tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
  tmux new-session -d -s "$SESSION_NAME" "$COMMAND"
fi

tmux switch-client -t "$SESSION_NAME"
